# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3dad12ea6e0966d7fcefe4fedeadb38f"
name = "Downpay"
application_url = "https://downpay.onrender.com"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-07"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "https://example.com/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "https://example.com/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,write_customers,read_orders,write_orders,read_products,write_products,read_purchase_options,write_purchase_options,read_content,write_content,read_themes,write_themes,unauthenticated_read_content"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://downpay.onrender.com/api/auth/callback"
]
